language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - pear channel-discover pear.phpunit.de
  - pecl install phpunit/test_helpers
  - composer self-update
  - composer install

script:
  - phpunit

after_script:
  - php vendor/bin/coveralls -v
